### PR TITLE
why not support org?

### PR DESCRIPTION
**Pull request by worthmine**
use Carp and replace die to croak, add ORG parameter

### CODE REVIEW

**Comment by kablamo** [comment]
I really appreciate the pr @worthmine !  Unfortunately I won't get a chance to review this until June 13th at the earliest.  Very sorry about that.

**Comment by worthmine** [comment]
I don’t hurry about that. thx

**Comment by ranguard** [comment]
@worthmine if you have the time and can rebase this, and get the tests passing, I'll get this merged and deployed.

**Comment by worthmine** [comment]
Now I'm writing what should I do with Moose and it's works well.
But I can't write the test! Because I have not written it never.

Anyway, I will make public what I wrote when I have the time to do.

**Comment by ranguard** [comment]
@worthmine The existing tests are failing (see the pull request on github) - the Travis CI link - that's what needs to be updated to pass.

Let me know if you need any help - many thanks

**Comment by worthmine** [comment]
@ranguard Hey I’ve  just written the [patch](https://github.com/worthmine/text-vcard) passing the tests!
but i can't  make new pull request with this.

**Comment by worthmine** [comment]
I could! please check pr #45

**Comment by ranguard** [comment]
@worthmine looks good - I'll give it a day for anyone to feedback on then merge and deploy - thank you so much.

Closing this pull in favour of #45

**Pull request closed without merging**
